# Generated by Django 4.2.2 on 2023-08-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markdown_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='markdown',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
