# Generated by Django 4.2.2 on 2023-08-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markdown_app', '0002_markdown_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='markdown',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
