# Generated by Django 4.2.2 on 2023-08-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markdown_app', '0003_markdown_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('markdownID', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
